import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, Building2, CalendarDays, FileText, MessageSquareText, Sparkles } from "lucide-react";
import { Shell } from "@/components/shell";
import { getSnapshot } from "@/lib/data";
export const dynamicParams = false;
export function generateStaticParams() { return getSnapshot().interviews.map(i => ({ id: i.id })); }
export async function generateMetadata({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; return { title: getSnapshot().interviews.find(i => i.id === id)?.title || "面经未找到" }; }
export default async function Detail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const data = getSnapshot(); const interview = data.interviews.find(i => i.id === id); if (!interview) notFound();
  const parts = data.chunks.filter(c => c.interview_id === id).sort((a, b) => a.start - b.start);
  const raw = Array.from(interview.raw);
  return <Shell><div className="mx-auto max-w-4xl reveal"><Link href="/" className="mb-8 inline-flex items-center gap-2 text-xs text-stone-500 hover:text-[#215e4e]"><ArrowLeft size={15}/>返回面经资料库</Link><div className="mb-5 flex gap-2"><span className="rounded-md bg-[#e8f0e2] px-3 py-1 text-xs text-[#658355]">{interview.category}</span>{data.demo && <span className="rounded-md bg-[#f0ecdf] px-3 py-1 text-xs text-[#928569]">含演示处理</span>}</div><h1 className="text-balance text-3xl font-semibold leading-snug sm:text-4xl">{interview.title}</h1><div className="mt-5 flex flex-wrap items-center gap-4 text-xs text-stone-500"><span className="flex items-center gap-1.5"><Building2 size={14}/>{interview.company || "公司未注明"}</span><span>{interview.role || "岗位未注明"}</span><span className="flex items-center gap-1.5"><CalendarDays size={14}/>{interview.interview_date || "面试日期未注明"}</span></div><div className="mt-5 flex flex-wrap gap-2">{interview.tags.map(t => <Link key={t} href={`/?tag=${encodeURIComponent(t)}`} className="rounded-lg border border-[#dfe6d8] px-3 py-1 text-xs text-[#718566]"># {t}</Link>)}</div>
    <section className="my-9 rounded-2xl border border-[#dbe7d5] bg-[#eef4e9] p-6 sm:p-7"><h2 className="mb-3 flex items-center gap-2 text-sm font-semibold text-[#406446]"><Sparkles size={17}/>{data.llm_provider === "mock" ? "整理摘要 · 演示规则" : "AI 总结"}</h2><p className="text-sm leading-8 text-[#60745b]">{interview.summary}</p><p className="mt-4 text-[10px] text-[#93a18c]">整理内容仅供快速回顾，请以完整原文为准。</p></section>
    <section className="mb-9"><h2 className="mb-5 flex items-center gap-2 text-lg font-semibold"><MessageSquareText size={19} className="text-[#6d8764]"/>面试问题<span className="ml-1 rounded-md bg-[#e8ede3] px-2 py-0.5 text-xs text-[#6f8662]">{interview.questions.length}</span></h2>{interview.questions.length ? <ol className="space-y-3">{interview.questions.map((q, index) => <li key={index} className="rounded-xl border border-[#e2e7dc] bg-white px-5 py-4"><div className="flex gap-3"><span className="mt-0.5 text-xs tabular-nums text-[#95a58a]">{String(index + 1).padStart(2,"0")}</span><p className="text-sm leading-7">{q.text}</p></div><details className="ml-7 mt-2 text-xs text-stone-500"><summary className="cursor-pointer">查看原文依据</summary><blockquote className="mt-2 border-l-2 border-[#d5e0ce] pl-3 leading-6">{q.evidence}</blockquote></details></li>)}</ol> : <p className="text-sm text-stone-500">原文未提取到明确的面试题。</p>}</section>
    <section className="rounded-2xl border border-[#e2e7dc] bg-white p-6 sm:p-8"><h2 className="mb-6 flex items-center gap-2 border-b border-[#ebeee6] pb-5 text-lg font-semibold"><FileText size={19} className="text-[#6d8764]"/>完整原文<span className="ml-auto text-[10px] font-normal text-stone-400">保留原始内容</span></h2><div className="whitespace-pre-wrap break-words text-[14px] leading-8 text-[#63705e]">{parts.length ? <>{raw.slice(0, parts[0].start).join("")}{parts.map((part, index) => <span key={part.id} id={part.id}>{raw.slice(part.start, parts[index + 1]?.start ?? raw.length).join("")}</span>)}</> : interview.raw}</div></section>
    </div></Shell>;
}
